#[shell]
#program = "/usr/local/bin/tmux"
#args=["new", "-s", "main", "-n", "main_window"]
[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "MesloLGS Nerd Font"

[window]
opacity = 0.96
# blur = true
# decorations = "None"
# startup_mode = "Fullscreen"
option_as_alt = "OnlyLeft" # Mac-only

[general]

# General
working_directory = "None"
# Import
import = [
    "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

